### ISSUE TITLE
FromHybrid parameter attribute for Core 2.1+

### ISSUE THREAD

**Issue by jasonycw** [billbogaiv/hybrid-model-binding#13]
Hi, is the FromHybrid not working for .NET Core 2.1+?

![image](https://user-images.githubusercontent.com/4518597/43629938-595b4fa8-9731-11e8-9894-9a398b7a083e.png)

Using `[From(Source.____)]` for the property seems ok but when using `[FromHybrid]` for the parameter is not, or am I using FromHybrid incorrectly?

![image](https://user-images.githubusercontent.com/4518597/43629911-3ff5172e-9731-11e8-8fac-0d8297e1bb52.png)

**Comment by billbogaiv** [comment]
*Apologies for taking longer to respond. I did not have notifications turned-on for this repo.*

~At a bare minimum, you'll **need** the `[From(...`]-attributes on your model's properties.~ The `[FromHybrid]` is optional depending on how you configured your app. services and the format of the controller-action.

If your setup does the same thing as the sample: https://github.com/billbogaiv/hybrid-model-binding/blob/be84c68fe13a458c54a8cc33900502c9f76923aa/samples/AspNetCoreWebApplication/Startup.cs#L23-L34 and your controller-action only has one parameter (i.e. your model), you don't need the `[FromHybrid]`-attribute (it's optional). The attribute is **required** if you don't follow this convention. Otherwise, the binding processes won't know to select the hybrid binder.

At some point, I will update the README to include this additional info.

**Comment by billbogaiv** [comment]
I have not been able to duplicate this problem using the most-recent version: https://www.nuget.org/packages/HybridModelBinding/0.14.0. I'm closing the issue, but if you still have problems on this version, open this issue again and possibly post more info. so I can duplicate your exact setup.
