### ISSUE TITLE
CQRS mappings with [FromHybrid]

### ISSUE THREAD

**Issue by aefox** [billbogaiv/hybrid-model-binding#34]
Hello,

I'm trying to do some mappings in the direction of CQRS with `[FromHybrid]` in the controller actions.

One controller contract example looks like this:
```C#
[HttpPost("{organisationId}/teams")]
public async Task<ActionResult<Team>> CreateTeamAsync([FromHybrid] CreateTeamCommand createTeamCmd)
```
Here's what I've tried so far:
```C#
public class CreateTeamCommand
{
    public readonly Guid OrganisationId;
    public readonly string Name;

    public CreateTeamCommand(Guid organisationId, string name)
    {
        OrganisationId = organisationId;
        Name = name;
    }
}
```
and
```C#
public class CreateTeamCommand
{
        public Guid OrganisationId { get; internal set; }
        public string Name { get; internal set; }
}
```

Unfortunately neither works. The only one that works is the standard
```C#
public class CreateTeamCommand
{
    public Guid OrganisationId { get; set; }
    public string Name { get; set; }
}
```

Any ideas on this? Personally I would love to have support for this. I would also consider contributing if this is feasible to implement and if you hint me the direction.

**Comment by billbogaiv** [comment]
The second-scenario is definitely supported. Make sure you're on the latest-version: https://www.nuget.org/packages/HybridModelBinding/0.15.0. Reflection is used to set values ~as long as the property itself is `public`~. I created a sample locally to confirm the behavior works as-expected. Is your work available as a repo. on GitHub I can check out?

**Comment by aefox** [comment]
Hi @billbogaiv and thanks for your response. I just created an extremely simple repo with various scenarios ([here](https://github.com/aefox/FromHybridTests)). From my tests, scenarios 1, 2 and 6 are failing (6 here is the one you mention it's working for you, for me it is still failing). Scenarios 3,4 and 5 are working fine.

The weirdest scenario is still 6. For some reason the `Id` property is resolved correctly from the route params while the `Name` property is not.

Let me know if I can be of any help.

**Comment by billbogaiv** [comment]
I've looked at your sample and identified a couple different issues. One has an easy solution and the other not so much 😟.

## General notes

Assuming you're using the library as-is and not creating derived instances of `HybridModelBinderProvider`...

The library uses [BodyModelBinder](https://github.com/aspnet/AspNetCore/blob/7a26d27e8b7f67a1ac80532e5872bfde6c28f952/src/Mvc/Mvc.Core/src/ModelBinding/Binders/BodyModelBinder.cs) for initially binding all requests. **For `GET`-requests, nothing gets bound since there is no request-body, but an instance of the model is still created**. Internally, this class uses [NewtonsoftJsonInputFormatter](https://github.com/aspnet/AspNetCore/blob/7a26d27e8b7f67a1ac80532e5872bfde6c28f952/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonInputFormatter.cs#L114-L244) (*.NET Core 3–previous versions use JsonInputFormatter, but their implementations are mostly identical for our purposes*). The latter is what actually deserializes the request into the controller-action model. The process follows Json.NET rules, etc.

## Cmd6 test *(the easy solution)*

If you know your property *might* be part of the request-body, decorate it with the `[JsonProperty]`-attribute. This tells Json.NET to set the property regardless of setter-visibility (by-default it only does it for `public`-properties/setters).

```csharp
public class Cmd6
{
    public int Id { get; internal set; }

    [JsonProperty]
    public string Name { get; internal set; }
}
```

## Cmd1 and Cmd2 ⛈

Building upon how the model-instance is created, for these `GET`-requests, `HybridModelBinding` only works with `public`-properties that *also* have setters (visibility makes no difference). `readonly` and `getter`-only properties won't currently work. Additionally, `fields` won't work even if they're `public` (`public int Id`).

## Conclusions

I'm in the very early stages of thinking how to revamp the whole approach and account for models that have parameterized-constructors. It would change a lot since the current approach is more incremental and assumes having a model-instance rather than building-up a collection of values and then hydrating the model. **I will create an issue, but don't have any time-table for completion**.

**Comment by billbogaiv** [comment]
This might make clearer the intent of the library (*it helped me think of a better way to describe the library*)... Think of `HybridModelBinding` more as an aggregator of model-binders and value-providers. It allows you to define what binders/providers you want to apply to a request and the order in which those things ultimately set properties on a request-model (and also whether a provider can override another).

**Comment by aefox** [comment]
Thanks a lot for taking the time to reply to this issue @billbogaiv 👍 . Everything is definitely clearer and makes total sense.

Couple of things to note:
1. I totally forgot to mention it initially, but I'm adding it here now in case someone else will be checking this issue in the future, I am indeed using the latest version, which at this moment is 0.15.0
2. Also correct, I am using the library as is
3. In the end I am choosing to go with a model with `private int Id { get; private set; }` and a `constructor(int id)` as this works as well and better reflects my definition of the model (the `[JsonProperty]` attribute, while it works, it is just "noise" that doesn't have anything to do with my model or it's business)

Again, thanks a lot for your responses and for this lib. I am definitely loving my controllers and logic a lot more right now lol 👍 🥇 .

**Comment by ikcehcus** [comment]
Case when I use CQRS still does not work on version 0.18

Framework: .net 5

**Startup.cs:**

`services.AddMvc().AddHybridModelBinder()`

**Controller:**

```
[Authorize(Policy = AuthPolicies.NetworkConfigure)]
[HttpPost("{id:guid}")]
[ProducesResponseType((int)HttpStatusCode.NoContent)]
[ProducesResponseType((int)HttpStatusCode.NotFound)]
[ProducesResponseType((int)HttpStatusCode.BadRequest)]
public async Task<ActionResult> Update([FromHybrid] Update command)
{
  await Mediator.Send(command);
  return NoContent();
}
```
**Command:**

```
 public class Update : ICommand
  {
    public Update(Guid id, string name)
    {
      this.Id = id;
      this.Name = name;
    }

    public Guid Id { get; set; }
    public string Name { get; set; }
  }
```


**Error:**

> {
>   "errors": {
>     "command": [
>       "The command field is required."
>     ]
>   },
>   "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
>   "title": "One or more validation errors occurred.",
>   "status": 400,
>   "traceId": "00-4c73b04f993a81469e16dcfb7615343e-8bdcc7c2c571cb43-00"
> }
> 
> Response code: 400 (Bad Request); Time: 2472ms; Content length: 247 bytes
